/*
 * TheGamesDB API
 *
 * API Documentations
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gamesdb

// GamesByGameIdAllOfInclude struct for GamesByGameIdAllOfInclude
type GamesByGameIdAllOfInclude struct {
	Boxart   GamesByGameIdAllOfIncludeBoxart   `json:"boxart"`
	Platform GamesByGameIdAllOfIncludePlatform `json:"platform"`
}
