/*
 * TheGamesDB API
 *
 * API Documentations
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gamesdb

// Developer struct for Developer
type Developer struct {
	Id   int32  `json:"id"`
	Name string `json:"name"`
}
