/*
 * TheGamesDB API
 *
 * API Documentations
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gamesdb

// ImageBaseUrlMeta struct for ImageBaseUrlMeta
type ImageBaseUrlMeta struct {
	Original           string `json:"original"`
	Small              string `json:"small"`
	Thumb              string `json:"thumb"`
	CroppedCenterThumb string `json:"cropped_center_thumb"`
	Medium             string `json:"medium"`
	Large              string `json:"large"`
}
