/*
 * TheGamesDB API
 *
 * API Documentations
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gamesdb

// GamesByGameIdAllOfIncludeBoxart struct for GamesByGameIdAllOfIncludeBoxart
type GamesByGameIdAllOfIncludeBoxart struct {
	BaseUrl ImageBaseUrlMeta       `json:"base_url"`
	Data    map[string][]GameImage `json:"data"`
}
