/*
 * TheGamesDB API
 *
 * API Documentations
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gamesdb

// PlatformSkinny struct for PlatformSkinny
type PlatformSkinny struct {
	Id    int32  `json:"id"`
	Name  string `json:"name"`
	Alias string `json:"alias"`
}
