/*
 * TheGamesDB API
 *
 * API Documentations
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gamesdb

// DevelopersAllOfData struct for DevelopersAllOfData
type DevelopersAllOfData struct {
	Count      int32                `json:"count"`
	Developers map[string]Developer `json:"developers"`
}
