/*
 * TheGamesDB API
 *
 * API Documentations
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gamesdb

// PublishersAllOfData struct for PublishersAllOfData
type PublishersAllOfData struct {
	Count      int32                `json:"count"`
	Publishers map[string]Publisher `json:"publishers"`
}
