/*
 * TheGamesDB API
 *
 * API Documentations
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gamesdb

// GenresAllOfData struct for GenresAllOfData
type GenresAllOfData struct {
	Count  int32            `json:"count"`
	Genres map[string]Genre `json:"genres"`
}
