/*
 * TheGamesDB API
 *
 * API Documentations
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gamesdb

// GamesByGameIdV1AllOfInclude struct for GamesByGameIdV1AllOfInclude
type GamesByGameIdV1AllOfInclude struct {
	Boxart   GamesByGameIdAllOfIncludeBoxart `json:"boxart"`
	Platform map[string]PlatformSkinny       `json:"platform"`
}
