/*
 * TheGamesDB API
 *
 * API Documentations
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gamesdb

// UpdateModel struct for UpdateModel
type UpdateModel struct {
	EditId    int32  `json:"edit_id,omitempty"`
	GameId    int32  `json:"game_id,omitempty"`
	Timestamp string `json:"timestamp,omitempty"`
	Type      string `json:"type,omitempty"`
	Value     string `json:"value,omitempty"`
}
