/*
 * TheGamesDB API
 *
 * API Documentations
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gamesdb

// PlatformsByPlatformNameAllOfData struct for PlatformsByPlatformNameAllOfData
type PlatformsByPlatformNameAllOfData struct {
	Count     int32      `json:"count"`
	Platforms []Platform `json:"platforms"`
}
