/*
 * TheGamesDB API
 *
 * API Documentations
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gamesdb

// Platform struct for Platform
type Platform struct {
	Id         int32  `json:"id"`
	Name       string `json:"name"`
	Alias      string `json:"alias"`
	Icon       string `json:"icon"`
	Console    string `json:"console"`
	Controller string `json:"controller"`
	Developer  string `json:"developer"`
	Overview   string `json:"overview,omitempty"`
}
