/*
 * TheGamesDB API
 *
 * API Documentations
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gamesdb

// GamesByGameIdAllOfIncludePlatform struct for GamesByGameIdAllOfIncludePlatform
type GamesByGameIdAllOfIncludePlatform struct {
	Data map[string]PlatformSkinny `json:"data"`
}
